spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root_yu
    password: Ykx19980402
    url: jdbc:mysql://rm-wz9025onlixw58p33.mysql.rds.aliyuncs.com:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    session:
      timeout: 120